### PR TITLE
Fix type definition

### PR DESCRIPTION
**Pull request by cubabit**
This is a fix to the type definitions

### CODE REVIEW

**Comment by lazywithclass** [comment]
Hello, thanks for this! Does it address https://github.com/lazywithclass/winston-cloudwatch/issues/104?

**Comment by cubabit** [comment]
Yes I believe it does

**Comment by cubabit** [comment]
Any ideas when this can get released?

**Comment by lazywithclass** [comment]
Yes sorry I was on vacation, I will do it today.

**Comment by lazywithclass** [comment]
winston-cloudwatch@2.0.6 published, sorry for the delay

**Pull request merged**
