### PR TITLE
Fixed jsonMessage formatting

### PR DESCRIPTION
**Pull request by TimJohns**
It looks like the jsonMessage flag had a typo in the name, so I fixed it and added a corresponding unit test.

### CODE REVIEW

**Comment by TimJohns** [comment]
Looks like I have mockery installed locally but didn't add it to the package. Doh!

**Comment by TimJohns** [comment]
Builds fine with 5.5.0, but looks like I broke it on 10.44 that the build server is using. I'll install that locally and get it running there.

**Comment by TimJohns** [comment]
Overall coverage for the module actually increased, since I added index.js under test as well. The percentage decreased because there's more code under test.  I have two more PRs to submit after this one, each of which increases coverage on the newly-under-test index.js as well.

**Comment by lazywithclass** [comment]
Hey, thanks for this! I'll have a look this evening and come back with comments or a new version :)

**Comment by lazywithclass** [comment]
I had a look at it, thanks again for taking the time to code this.

I have two observations:

* what are you talking about when you say version 5.5.0 and 10.44?
* I saw you used `mockery` instead of `sinon` I've always used the latter but I'm open to change, does `mockery` add something that `sinon` does not? If so, what? If we decide to use `mockery` I would say that, for the test file you introduced we should just use that, what do you think?

Plus the one from before

> It's not really clear to me why the ES6 syntax was creating problems, could you please expand on that?

Let me know so we can see how to progress on this :)

**Comment by TimJohns** [comment]
Thanks Alberto, 

> what are you talking about when you say version 5.5.0 and 10.44?
> It's not really clear to me why the ES6 syntax was creating problems, could you please expand on that?

I believe both observations are related. The unit tests ran successfully, locally on my Mac, where I was currently using Node 5.5.0.  Once I checked them in, however, the build server (which is running node 0.10.44) failed to build. I downgraded locally to 0.10.44 as well, and determined that the build was failing because the ES6 class semantics weren't fully introduced until Node 4.0.0 per https://github.com/nodejs/node/blob/v4.0.0/CHANGELOG.md. This hadn't been a problem before, because the index.js file that contained the nice class semantics wasn't previously under test.

> I saw you used mockery instead of sinon I've always used the latter but I'm open to change, does mockery add something that sinon does not? If so, what? If we decide to use mockery I would say that, for the test file you introduced we should just use that, what do you think?

I typically use mockery and sinon together to solve different problems. The major functionality I use mockery for is to inject the dependancies that index.js explicitly pulls in with requires(). I'm not sure how sinon can override require(). I do feel it's important to avoid requiring the aws-sdk and winston modules, since they could execute code at the time require loads them. 

On a related side note, as I look over this again, I would also suggest removing the require('aws-sdk') from test/cloudwatch-integration.js. 

I do typically use sinon to add the spy functions to the inline stubs I create (much like is done in test/cloudwatch-integration.js), but in this case the stubs I needed were simple enough that I barely needed to, so you might be noting some difference in stub style, unrelated to mockery.  If the difference in style is distracting, please let me know - I can probably make the stubs in test/index.js look a little more like the stubs in test/cloudwatch-integration.js.

Thanks again for creating this module, I'm finding it tremendously useful!

- Tim

**Comment by lazywithclass** [comment]
I was just concerned about hearing why you chose that module, the reasoning you presented is a valid point.

I think we can have travis-ci to use node v5.* by changing [this line](https://github.com/lazywithclass/winston-cloudwatch/blob/master/.travis.yml#L3) ([here](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against) the availabile versions), I'll try it this evening when I get home.

If I can manage to keep the `class` syntactic sugar I think I'll keep it, othwerwise I'll go with your commit where you removed it. Either way I'll merge and this will be in 1.1.0.

Thanks again.

**Comment by TimJohns** [comment]
Thanks!  

 I really like the new class syntax as well, but I'd (unfortunately) recommend keeping the backward compatible code, at least as far back as Nodee version 0.12.12.  As of today, 0.12.12 is the most recent version currently supported by the nodejs layer in Amazon OpsWorks.  That the OpsWorks config lags a little can be frustrating for a number reasons, I wouldn't want to add to that, and this module indeed makes an awesome match for an OpsWorks stack implementation otherwise.

- Tim

**Comment by lazywithclass** [comment]
@TimJohns I've seen you're quite active on your branch, do you want any help to have those changes land in winston-cloudwatch?  

Sorry I'm writing here, I wasn't able to open an issue on your repo.

**Comment by TimJohns** [comment]
You bet.  I'm not quite happy with the close() semantics I added, but I'll isolate the other stuff into a couple of branches and submit PRs.

**Pull request merged**
