### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nodkz**
By default creation time is not displayed. So my first solution was to add time via `formatMessage`, but after that found gear ;).

### CODE REVIEW

**Comment by lazywithclass** [comment]
Thanks

**Comment by lazywithclass** [comment]
I just updated the README because the gear for me is in the top right corner, not left, could you confirm this?

**Comment by nodkz** [comment]
yep, right corner.

**Comment by lazywithclass** [comment]
👍

**Pull request merged**
