### PR TITLE
add Error Handler function support

### PR DESCRIPTION
**Pull request by yoiang**
@lazywithclass thanks for the great integration transport! This is a simple patch that allows us to maintain control over the console and handle these errors in a more precise way!

### CODE REVIEW

**Comment by yoiang** [comment]
@lazywithclass thanks for the great integration transport! This is a simple patch that allows us to maintain control over the console!

**Comment by lazywithclass** [comment]
Thank you for this :)
Could you please consider adding testing to it?

**Comment by lazywithclass** [comment]
I will use [this branch](https://github.com/lazywithclass/winston-cloudwatch/tree/adorkable-fork-for-error-handler) to add tests and slightly change the code in the next couple of days, let me know what you think.

**Comment by yoiang** [comment]
@lazywithclass sorry for the late reply! I should have included a test in the first place. Of course, change the code however you'd like! :)

**Comment by lazywithclass** [comment]
@yoiang let me know what you think: https://github.com/lazywithclass/winston-cloudwatch/commit/2e4f8962c1fe750be0b7c6320d79cc82f7d0fec4

I will merge tomorrow, I will probably have to do some cleaning on those tests.

**Comment by yoiang** [comment]
@lazywithclass it looks great :)

**Comment by lazywithclass** [comment]
@yoiang added in v1.2.0

**Comment by yoiang** [comment]
@lazywithclass  🚀 thanks again :)

**Pull request closed without merging**
