### PR TITLE
When kthxbye is called - Keep submitting until empty 

### PR DESCRIPTION
**Pull request by avnerenv0**
Solves https://github.com/lazywithclass/winston-cloudwatch/issues/117

### CODE REVIEW

**Comment by lazywithclass** [comment]
Look ok for me, thanks for the effort you've put in writing this.

Have you already tested this in your environment and does it solve the problem you were having?

**Comment by avnerenv0** [comment]
@lazywithclass Yes this solved the issue for us.
Do you think that `kthxbye` should also have timeout value, just so we don't end up running infinite loops incase there is something wrong?

**Comment by lazywithclass** [comment]
That's a good idea, we don't want the library preventing environments like AWS Lambda from exiting.

If you could add that then I'd say this is ready for merge!

**Comment by avnerenv0** [comment]
@lazywithclass I add that.
All the tests are passing but somehow I'm seeing this in the test output - 
```
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․ERROR
ERROR
ERROR
ERROR
ERROR
․․․․

  52 passing (70ms)
```
Any ideas?

**Comment by lazywithclass** [comment]
Yes sorry about this, I'm not actively using this module since years, just maintaining it with a huge help from the community, so things like this easily slip by.

This is the fix

```
diff --git a/test/index.js b/test/index.js
index 3a4c335..1f73a2b 100644
--- a/test/index.js
+++ b/test/index.js
@@ -205,9 +205,7 @@ describe('index', function() {
       });

       afterEach(function() {
-        stubbedCloudwatchIntegration = {
-          upload: sinon.spy()
-        };
+        stubbedCloudwatchIntegration.upload = sinon.spy();
         console.error.restore();
       });
```

**Comment by avnerenv0** [comment]
@lazywithclass Don't be sorry you're doing a great job 🙏 
Fix applied, Ready for merge AFAIK

**Comment by lazywithclass** [comment]
I will merge this tonight EU time. Thanks for the effort and for waiting!

**Comment by avnerenv0** [comment]
FYI
We still have issues with this, apparently this fix doesn't solve everything.
It works great locally but in an AWS ECS Container we are still getting problems with logs missing when the container exits too quickly, even though we are waiting for `kthxbye` to complete. 

We'll try to get to the root cause but I'm not sure it will happen in the near future.

**Comment by lazywithclass** [comment]
Ok I will have a look tonight, but this surely seems an improvement.

**Comment by lazywithclass** [comment]
What would be the best strategy for me to test this and help you fix the problem?
Should I just use a lambda, inject some logs, and see what happens?

I thought about this, and not pushing a new version if the issue if not resolved seems to be bettere IMHO, what do you think?
BTW, I've released winston-cloudwatch@2.2.0 which contains huge dependencies update and a small fix (details here https://github.com/lazywithclass/winston-cloudwatch/pull/116), it might be a good idea to apply the new version and see how things go from there.

**Comment by avnerenv0** [comment]
Our use-case is running in a docker container, as en ECS Task.
We create a logger, generate some logs, wait for the `kthxbye`callback, and then `process.exit`.

I'm good with not pushing a new version here until we resolve this, we are using the forked version anyway.

**Comment by alaycock** [comment]
@avnerenv0 I know this is quite outdated now, but any chance of this getting resolved or merged soon? We're running into the same issue, and have found a potential workaround, but definitely would like to resolve this at the library-level instead.

If you are using a fork, is that something you might be able to share?

**Comment by avnerenv0** [comment]
@alaycock we are using the forked version in - https://github.com/env0/winston-cloudwatch
Regarding the merge - that's up to @lazywithclass

**Comment by lazywithclass** [comment]
Hello and sorry for the huge delay in the answers, I have more free time now.

@avnerenv0 I will test these changes as close to your environment as I can, anyway, if I've understood correctly you're already using them in your fork, right?
If so I'm more confident to merge.

**Comment by avnerenv0** [comment]
@lazywithclass no need to apologise - thanks for maintaining this package 🙏 
We've been using our fork for about 6 months now. It works well.

**Comment by lazywithclass** [comment]
winston-cloudwatch@2.3.2 is published with your changes, thanks for the effort!

**Comment by avnerenv0** [comment]
@lazywithclass thanks!

**Comment by alaycock** [comment]
Thanks to both of you, I'll grab the new version and try it out!

**Comment by lazywithclass** [comment]
@alaycock if this doesn't work as expected please open a new issue referencing this PR, thanks!

**Pull request merged**
